### ISSUE TITLE
Other Phomemo printer repos

### ISSUE THREAD

**Issue by taylorjdlee** [vivier/phomemo-tools#10]
It seems there's a few other repos that worked on different Phomemo printers we should be able to add more driver support by taking a look into these repos:

Phomemo D30 (should be able to derive headers footers from here): https://github.com/polskafan/phomemo_d30/blob/master/print_text.py

M02s (already made a PR for this): https://github.com/privatwolke/phomemo-tools

M02 Pro (seems to similar to the M02s both are 300 dpi): https://github.com/noullove/phomemo-tools

T02 (was reversed with help from this project): https://github.com/iamjackg/esp32-phomemo-gameboy-printer

P12Pro, D35, D30 and M220 (Not too sure how much we can derive from here): https://github.com/Knightro63/phomemo

M03 (should be able to derive headers/footers from here): https://github.com/whitechip4/Phomemo-M03-Mod/blob/master/phomemo_m03.py

P12 (should be able to derive headers/footers from here): https://github.com/S1artie/InternetOfTrash/blob/master/labelprinter/labelprinter.py

But yeah it's a good start and it'll be nice to get this repo supporting as many Phomemo printers as possible!

**Comment by taylorjdlee** [comment]
@vivier @daig0rian let me know your thoughts!

**Comment by taylorjdlee** [comment]
So looking at this https://github.com/iamjackg/esp32-phomemo-gameboy-printer/blob/main/src/main.cpp it seems the T02 has the same protocol as the M02. So that should be an easy fix

**Comment by daig0rian** [comment]
Thanks for the valuable information. I didn't realize there were so many repositories, so it was helpful to get the big picture.
I looked at the headers and footers of each project for a bit. One project seemed to be using the dump as-is and avoiding parameter analysis. One project seemed to be trying to parse the parameters in detail and succeeding. One project appeared to be sending from a block marker with almost no headers.

I think it is worthwhile to include headers and footers that have been analyzed in detail. However, I was concerned that incorporating something with little consideration might exhaust repository owner with more inquiries from users who expected their printers to work well.

**Comment by taylorjdlee** [comment]
Yes I agree I guess we'll wait until more users come across this repo and want their printers supported
