### ISSUE TITLE
Phomemo Wireless Label Printer Model P12 info

### ISSUE THREAD

**Issue by Ed-k** [vivier/phomemo-tools#17]
I couldn't find any information about the Phomemo P12 so here are my notes from testing it. The Phomemo P12 USB protocol seems to be the same as the M110/M120/M220 so it was surprisingly easy to get it working. 
The width is 12 bytes (96 pixels). I only have tape media so I'm using media 0b (Continuous).
The P12 must be powered on after connecting it to USB power by pressing the button. It will work if the button is held down continuously so the button can be clamped or glued to keep it on permanently (so it turns back on automatically after power is interrupted).

FCC ID: 2ASRB-P12

USB info:
idVendor:                        0x4C4A = Vendor ID not listed with USB.org
idProduct:                       0x4155
bcdDevice:                       0x0100
iManufacturer:                     0x01
     English (United States)  "Jieli Technology"
iProduct:                          0x02
     English (United States)  "USB Composite Device"
iSerialNumber:                     0x03
     English (United States)  "1234567890ABCDEF"
bNumConfigurations:                0x01

**Comment by vivier** [comment]
Thank you for the information

**Comment by michaelnew** [comment]
Just wanted to say that gluing the button down was a great tip. I wanted to keep this T02 always on and that appears to be the only way to do it.
