### ISSUE TITLE
Question: Image printing size

### ISSUE THREAD

**Issue by TTang49** [vivier/phomemo-tools#2]
Hello sir,
I currently own the Phomemo M110 and my objective is to print a QR Code on a page (30*20mm).
Is it possible to print an image with specific settings or do I need to use another method (working on python)?
Many thanks

**Comment by vivier** [comment]
Hi,

you can use gLabel to print QR code.

I have some label sizes defined for the printer and installed under /usr/share/phomemo, you have only to copy phomemo-q22.xml  to ~/.config/libglabels/templates/phomemo-q22.template.

They will appear in the gLabels product list (Phomemo Q22).
